import { useNavigate } from 'react-router-dom'

const sectionClass = 'space-y-2'
const headingClass = 'text-lg font-semibold text-neutral-900 dark:text-white'
const bodyClass = 'text-sm leading-relaxed text-neutral-700 dark:text-neutral-300'
const listClass = 'list-disc space-y-1.5 pl-5 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300'

function TermsOfService() {
  const navigate = useNavigate()

  return (
    <div className="mx-auto max-w-md space-y-6 p-4 pb-16">
      <button
        type="button"
        onClick={() => navigate(-1)}
        className="text-sm font-medium text-neutral-600 dark:text-neutral-400"
      >
        ← Back
      </button>

      <div>
        <h1 className="text-2xl font-semibold text-neutral-900 dark:text-white">Terms of Service</h1>
        <p className="mt-1 text-xs text-neutral-500">Last updated 8 September 2026</p>
      </div>

      <p className={bodyClass}>
        These Terms of Service ("Terms") govern your use of Forged ("Forged", "we", "us", "our"),
        a fitness tracking app. By creating an account, you agree to these Terms. If you don't
        agree, don't use Forged.
      </p>

      <section className={sectionClass}>
        <h2 className={headingClass}>Minimum age</h2>
        <p className={bodyClass}>
          You must be at least 16 years old to create a Forged account. By signing up, you confirm
          that you meet this requirement.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Acceptable use</h2>
        <p className={bodyClass}>
          Forged lets you message other users and share photos and videos. When using these
          features, or any other part of the app, you agree not to post, send, or upload content
          that:
        </p>
        <ul className={listClass}>
          <li>Is illegal, or promotes or facilitates illegal activity.</li>
          <li>
            Is abusive, threatening, harassing, hateful, or intended to bully, intimidate, or
            demean another user.
          </li>
          <li>Is sexually explicit, or depicts or promotes violence or self-harm.</li>
          <li>Infringes someone else's intellectual property, privacy, or other rights.</li>
          <li>Impersonates another person, or is spam, a scam, or an unsolicited advertisement.</li>
          <li>Contains malware or anything designed to disrupt or damage the app or other users' devices.</li>
        </ul>
        <p className={bodyClass}>
          This applies to messages and attachments (photos and videos) sent to other users, as
          well as your profile and any other content you share on Forged. We may remove content
          that violates these rules and take action against the account responsible, including
          suspension or termination as described below.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Fitness disclaimer</h2>
        <p className={bodyClass}>
          Forged provides workout tracking, suggestions, and coaching guidance — including guidance
          generated by the "Your coach" AI feature — for informational and motivational purposes
          only. None of this is medical advice, and it isn't a substitute for professional medical
          guidance, diagnosis, or treatment.
        </p>
        <p className={bodyClass}>
          Consult a doctor or other qualified healthcare provider before starting a new exercise
          program, especially if you have a pre-existing health condition, injury, or any concerns
          about your fitness to exercise. You use Forged's workout suggestions, including
          AI-generated ones, at your own risk, and you're responsible for exercising safely and
          within your own limits.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Subscription and billing</h2>
        <p className={bodyClass}>
          Forged Premium is an optional paid subscription (currently £4.99/month) that unlocks
          the AI coach, advanced analytics, and free streak recovery. Some features, such as
          one-off streak restoral, may also be offered as a separate paid purchase. All payments
          are processed by Stripe, our third-party payment processor; we don't store your card
          details.
        </p>
        <ul className={listClass}>
          <li>
            Your subscription renews automatically each billing period until you cancel, and you'll
            be charged using the payment method on file.
          </li>
          <li>
            You can cancel anytime from{' '}
            <span className="font-medium text-neutral-900 dark:text-white">
              Premium → Manage billing
            </span>
            , which opens Stripe's billing portal. Cancelling stops future renewals, but you keep
            Premium access until the end of the billing period you've already paid for.
          </li>
          <li>Payments are non-refundable except where required by law.</li>
          <li>
            We may change subscription pricing or features going forward; we'll give you notice
            before any change takes effect for your next billing period.
          </li>
        </ul>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Account termination</h2>
        <p className={bodyClass}>
          You can delete your own account at any time from{' '}
          <span className="font-medium text-neutral-900 dark:text-white">
            Settings → Delete account
          </span>
          , which permanently deletes your account and associated data.
        </p>
        <p className={bodyClass}>
          We may suspend or terminate your account, with or without notice, if you violate these
          Terms — including the acceptable use rules above — or if we reasonably believe your
          account poses a risk to Forged, other users, or the operation of the app. Where
          reasonably possible, we'll tell you why. Terminating your account does not entitle you to
          a refund of any prepaid subscription period, except where required by law.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Disclaimers</h2>
        <p className={bodyClass}>
          Forged is provided "as is" and "as available," without warranties of any kind, express or
          implied, including as to accuracy, reliability, or fitness for a particular purpose. We
          don't guarantee that the app will be uninterrupted, error-free, or secure.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Limitation of liability</h2>
        <p className={bodyClass}>
          To the maximum extent permitted by law, Forged and its operators aren't liable for any
          indirect, incidental, special, consequential, or punitive damages, or any loss of data,
          revenue, or profits, arising from your use of — or inability to use — the app, including
          any reliance on workout suggestions or AI-generated coaching guidance. Our total liability
          for any claim relating to Forged is limited to the amount you paid us, if any, in the 12
          months before the claim arose. Nothing in these Terms limits liability that can't be
          limited under law, such as liability for death or personal injury caused by negligence, or
          for fraud.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Changes to these Terms</h2>
        <p className={bodyClass}>
          We may update these Terms as Forged changes. If we make material changes, we'll let you
          know in the app before they take effect. Continuing to use Forged after changes take
          effect means you accept the updated Terms.
        </p>
      </section>

      <section className={sectionClass}>
        <h2 className={headingClass}>Contact us</h2>
        <p className={bodyClass}>
          For any questions about these Terms, email us at{' '}
          <a
            href="mailto:forgedapplication@gmail.com"
            className="font-medium text-neutral-900 underline dark:text-white"
          >
            forgedapplication@gmail.com
          </a>
          .
        </p>
      </section>
    </div>
  )
}

export default TermsOfService
